### ISSUE TITLE
Fork on Github badge is not displayed with screen's between the sizes of 770px - 1100px

### ISSUE THREAD

**Issue by shubh1m** [fossasia/gci15.fossasia.org#635]
![screenshot from 2016-01-24 04 55 09](https://cloud.githubusercontent.com/assets/13465950/12533506/1a262936-c257-11e5-8f27-b0c99b676a62.png)

**Comment by sudo-panda** [comment]
I think this problem is solved
![foss](https://cloud.githubusercontent.com/assets/16690760/12535137/7bd30432-c29e-11e5-977e-8480ed96ccf0.PNG)
![foss1](https://cloud.githubusercontent.com/assets/16690760/12535143/acfe65ce-c29e-11e5-87ab-b9807fce345f.PNG)

**Comment by jigyasa-grover** [comment]
I think it still persists. The nav bar font size needs to be adjusted .

**Comment by mananwason** [comment]
Looks fine to me @jig08. Can you provide a screenshot where this issue still persists?

**Comment by jigyasa-grover** [comment]
Sure @mananwason 
Here it comes.
Chrome Version 47.0.2526.73 (64-bit)

![screenshot from 2016-01-24 13 52 18](https://cloud.githubusercontent.com/assets/9291400/12535206/bef3f9f8-c2a1-11e5-8012-d3d53b2d64b9.png)

**Comment by mananwason** [comment]
okay I think you're seeing the cached version. I used safari and chrome(Version 47.0.2526.111 (64-bit) and it is working fine here!!
<img width="1440" alt="screen shot 2016-01-24 at 1 59 17 pm" src="https://cloud.githubusercontent.com/assets/10570249/12535235/bf2fc054-c2a2-11e5-9127-9b67768224b1.png">
<img width="1440" alt="screen shot 2016-01-24 at 2 00 24 pm" src="https://cloud.githubusercontent.com/assets/10570249/12535250/ef2561e2-c2a2-11e5-8f1d-9396e3bfd558.png">

**Comment by sudo-panda** [comment]
And in Chrome Version 47.0.2526.111 m 64-bit it does not exist.
![foss2](https://cloud.githubusercontent.com/assets/16690760/12535261/4c076478-c2a3-11e5-9648-75f8ebc77194.PNG)

**Comment by Baidya99** [comment]
Can I something irrelevant of this topic

**Comment by sudo-panda** [comment]
Can I ask something irrelevant of this topic

**Comment by jigyasa-grover** [comment]
Sure @Baidya99

**Comment by sudo-panda** [comment]
How to tell someone via github that his code is wrong.

**Comment by jigyasa-grover** [comment]
@mananwason  I have this issue on Firefox 41.0 too (not viewing a cached version this time)

![screenshot from 2016-01-24 14 10 04](https://cloud.githubusercontent.com/assets/9291400/12535303/4ee22664-c2a4-11e5-814c-0285297c8b89.png)

**Comment by jigyasa-grover** [comment]
@Baidya99 
You could create an issue on his/her repository.
In my opinion, that is the best option to put forward your thoughts about his/her code.
Rest, it all varies from person to person :)

**Comment by sudo-panda** [comment]
The first two images I sent were from Firefox 44.0

**Comment by sudo-panda** [comment]
Actually I copied the FOSS quiz(in the gallery section of fossasia website) and tried to compile it but it showed an error.

**Comment by sudo-panda** [comment]
*FOSS Quiz code

**Comment by jigyasa-grover** [comment]
Okay.. ?

**Comment by Yathannsh** [comment]
Given the positioning, size and shape of the Fork Me ribbon it will be hard to make it responsive. 
I suggest adding a fork me button in the navigation instead. Thoughts? @jig08 @mananwason

**Comment by mananwason** [comment]
@Yathannsh If it's visible enough, we can leave it as it is. If the issue that @jig08 pointed still persists, we can think about adding a button.

**Comment by Yathannsh** [comment]
@mananwason the visibility is subjective to the user's screen size, just as @jig08 people with screen widths less than 1100px will be facing this problem.

**Comment by jigyasa-grover** [comment]
+1 @Yathannsh ,   I just tested on another device with a larger size and it works fine on it.
But issue persists on smaller screens.

**Comment by mananwason** [comment]
Just tested on a nexus 5, looks fine there as well. :confused: 
![screenshot_20160124-164035](https://cloud.githubusercontent.com/assets/10570249/12535909/799494ea-c2b9-11e5-9c51-22846f75e732.png)

**Comment by mananwason** [comment]
Oh Now I get it. When I resize my browser to a certain width, the navigation buttons start appearing and since they can't be fixed into the space along the fossasia logo, they overflow to the next line and when the space for them becomes sufficient, the fork me logo is visible.

**Comment by Yathannsh** [comment]
@mananwason , right, this issue persists for user's with screen's between the sizes of 770px -  1100px!

**Comment by jigyasa-grover** [comment]
@mananwason Exactly !

**Comment by yasoob** [comment]
We can easily resolve this by using a media query. Let me push a fix.

**Comment by mananwason** [comment]
Awesome. Go ahead :+1:

**Comment by yasoob** [comment]
Done :smile:
